package de.htwg.se.rummy.controller.component

object ContState extends Enumeration {


  val MENU, INSERTING_NAMES, P_TURN, P_FINISHED, TABLE_NOT_CORRECT,
  NOT_ENOUGH_PS, START, P_INSERTED, ENOUGH_PS, CREATED, INSERTED_NAME, P_WON, P_DOES_NOT_OWN_TILE,
  CANT_MOVE_THIS_TILE, PLAYER_REMOVED, UNDO_LAY_DOWN_TILE, BAG_IS_EMPTY,
  LOAD_FILE,
  STORE_FILE,
  COULD_NOT_LOAD_FILE = Value


}
